apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "podlogreader-controller.serviceAccountName" . }}
  namespace: {{ include "podlogreader-controller.fullname" . }}
  labels:
    {{- include "podlogreader-controller.labels" . | nindent 4 }}
